---
  - name: so especifico
    hosts: all
    tasks:
      - name: ola mundo familia RedHat
        shell: 'echo ola mundo'
        when: (ansible_os_family == "RedHat")
    
      - name: ola mundo familia Debian
        shell: 'echo ola mundo'
        when: (ansible_os_family == "Debian" or ansible_distribution_version == "20.04")
...