version: '3'

services:
  ansible_server:
    build: .
    container_name: ansible_server
    command: ["tail", "-f", "/dev/null"]
    hostname: ansible_server
    volumes:
      - .:/root/ansible

  node1:
    build: .
    container_name: node1
    command: ["tail", "-f", "/dev/null"]
    hostname: node1

  node2:
    build: .
    container_name: node2
    command: ["tail", "-f", "/dev/null"]
    hostname: node2